version: '3.1'

services:
  # reactjs:
  #   image: .

  wordpress:
    image: wordpress
    # restart: always
    ports:
      - 8080:80
      - 443:443
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: onesinus
      WORDPRESS_DB_PASSWORD: ahmantap
      WORDPRESS_DB_NAME: wordpress-db
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    # restart: always
    environment:
      MYSQL_DATABASE: wordpress-db
      MYSQL_USER: onesinus
      MYSQL_PASSWORD: ahmantap
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: